<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>VoidUI</AssemblyName>
    <Version>1.0.0</Version>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DebugType>none</DebugType>
    <OutputPath>D:\Void-ui\_build\bin\</OutputPath>
    <BaseIntermediateOutputPath>D:\Void-ui\obj\</BaseIntermediateOutputPath>
    <ApplicationIcon>assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="assets\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Installer\**" />
    <None Remove="Installer\**" />
    <EmbeddedResource Remove="Installer\**" />
    <AvaloniaXaml Remove="Installer\**" />
    <AvaloniaResource Remove="Installer\**" />
  </ItemGroup>

  <ItemGroup>
    <None Include="presets\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="presets" />
  </ItemGroup>

</Project>
